services:
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9091:9090"
    volumes:
      - ./prometheus-config/prometheus.yaml:/etc/prometheus/prometheus.yaml
      - prometheus:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yaml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--storage.tsdb.retention.time=288h'
      - '--web.enable-lifecycle'
    restart: unless-stopped
    networks:
      - quarkus-net
    extra_hosts:
      - "host.docker.internal:host-gateway"  # This allows Prometheus to reach your host

  quarkus:
    container_name: quarkus-app
    image: marco1205/ocm-jvm
    ports:
      - "20400:20400"
    environment:
      PROMETHEUS_BASE_URL: http://100.109.12.45:9090
      APP_API_KEY: "set-your-apikey-here"
    cap_add:
      - NET_RAW
      - NET_ADMIN
    networks:
      - quarkus-net

volumes:
  prometheus:

networks:
  quarkus-net:
    driver: bridge
