quarkus:
  log:
    level: INFO
  hibernate-orm:
    schema-management:
      strategy: drop-and-create
    log:
      sql: true
  http:
    access-log:
      enabled: false

  datasource:
    db-kind: postgresql
    username: observer
    password: theOverlookingEagle
    jdbc:
      url: jdbc:postgresql://localhost:5432/observe_db
    devservices:
      enabled: true
      show-logs: true

  rest-client:
    prometheus-metrics-client:
      url: ${PROMETHEUS_BASE_URL}

my:
  occ:
    connect-file-path: ./connect-file/observe-connect-token
    token-length: 256